services:
  postgres:
    container_name: pg-ducbinh-dev
    image: postgres:12
    restart: always
    volumes:
      - db_data:/data/postgres
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - "5432:5432"
    expose:
      - "5432"
  postgres_exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: postgres_exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable"
    ports:
      - "9187:9187"
    depends_on:
      - postgres

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./devops/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER
      - GF_SECURITY_ADMIN_PASSWORD
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    depends_on:
      - postgres
      - prometheus
      - postgres_exporter
    ports:
      - "8080:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./devops/grafana/provisioning:/etc/grafana/provisioning
      - ./devops/grafana/dashboards:/var/lib/grafana/dashboards/
    entrypoint: ["/bin/bash", "-c", "/etc/grafana/provisioning/datasources/create_datasource.sh & /run.sh"]
volumes:
  db_data:
  grafana_data:
